version: '3.8'
services:
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: library_server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./kavita_data:/kavita/config
      - ./library/ebooks:/ebooks
